config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users do
  resources :memos
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :note, presence: true, length: { maximum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memos 
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_user
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  before_action :current_user
  
  def index
    @memos = Memo.all
    @memos = Memo.paginate(page: params[:page])
  end
  
  def new
    @user=User.find(params[:user_id])
    @memo = Memo.new
  end
  
  def show
    @memo = Memo.find_by(params[:user_id])
  end
  
  def create
    @memo = @user.memos.new(memo_params)
    if @memo.save
      flash[:success]="メモ新規作成しました。"
      redirect_to user_memos_url @user
    else
      flash.now[:danger] = "メモを作成できませんでした。"
      render :new
    end
  end
  
  def edit
    @memo = Memo.find_by(params[:user_id])
  end
  
  def update
    if @memo.update_attributes(memo_params)
      flash[:success] = "メモを更新しました。"
      redirect_to user_memo_url(@user, @memo)
    else
      render :edit
    end
  end
  
  def destroy
    @memo.destroy
    flash[:danger] = "メモを削除しました。"
    redirect_to user_memos_url @user
  end
  
  
  
  
  private
  
  def set_user
    @user=User.find(params[:user_id])
  end
  
  def memo_params
    params.require(:memo).permit(:title, :note, :user_id)
  end
  
  def set_memo
      unless @memo = @user.memos.find_by(id: params[:id])
        flash[:danger] = "権限がありません。"
        redirect_to user_memos_url @user
      end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def new
  end
  
  def create
     user = User.find_by(email: params[:session][:email].downcase)
     if user && user.authenticate(params[:session][:password])
       log_in user
       params[:session][:remember_me] == '1' ? remember(user) : forget(user)
       redirect_back_or user
     else
       flash.now[:danger] = "認証に失敗しました。"
       render :new
     end
  end
  
  def destroy
    log_out if logged_in?
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :current_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def show
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "新規登録しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end
  
  def edit
  end
  
  def destroy
    @user.destroy
    flash[:danger] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def set_user
      @user = User.find(params[:id])
  end
  
  def logged_in_user
      unless logged_in?
      　store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
  end
  
  def correct_user
      redirect_to(root_url) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_name = "")
    base_title = "メモアプリ"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def forget(user)
    user.forget # Userモデル参照
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def redirect_back_or(default_url)
    redirect_to(session[:forwarding_url] || default_url)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "メモアプリ", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? %>
        <% if current_user.admin? %>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My アカウント", current_user %></li>
              <li><%= link_to "メモ一覧", user_memos_path(@current_user) %></li>
              <li><%= link_to "メモ作成", new_user_memo_path(@current_user) %></li>
              <li><%= link_to "My アカウント編集", edit_user_path(@current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/memos/edit.html.erb
<% provide(:title, 'Edit Memo') %>
<h1>メモ編集修正</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @memo, url: user_memo_path(@user, @memo), method: :patch, local: true) do |f| %>
          
          
          <%= f.label :title, class: "label-signup" %>
          <%= f.text_field :title, class: "form-control" %>
            
          <%= f.label :note, class: "label-signup" %>
          <%= f.text_area :note, class: "form-control" %>

          
          <%= f.submit "更新", class:"btn btn-primary btn-form" %>
          <%= link_to "キャンセル", user_memo_path, class: "btn btn-default btn-form" %>
    <% end %>
  </div>
</div>

app/views/memos/index.html.erb
<% provide(:title, 'Index Memo') %>
<h1><%= @user.name %>のメモ一覧</h1>


<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <%= will_paginate %>
    <%= link_to "メモの追加", new_user_memo_path(@user), class: "btn btn-lg btn-primary pull-right" %>
    <table class="table table-condensed table-hover" id="table-users">
      <thead>
        <tr>
          <th>名前</th>
          <th>作成日</th>
        </tr>
      </thead>
      <tbody>
      <% @memos.each do |memo| %>
      <tr>
        <td><font size = "+1"><%= link_to memo.title, user_memo_path(@user, memo) %></font></td>
        <td><%= l(memo.created_at, format: :long) %></td>
        <td><%= link_to "削除", user_memo_path(@user, memo), method: :delete,
                data: { confirm: "#{@memo}を削除してよろしいですか？" },
                class: "btn btn-danger" %>
        </td>
      </tr>
      
      <% end %>
    </table>
    </tbody>
    <%= will_paginate %>
  </div>

app/views/memos/new.html.erb
<% provide(:title, 'New Memo') %>
<h1>新規メモ作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @memo, url: user_memos_path(@user), method: :post, local: true) do |f| %>
      
      <%= f.label :title, "タイトル", class: "label-signup" %>
      <%= f.text_field :title, class: "form-control" %>
      
      <%= f.label :note, "内容", class: "label-signup" %>
      <%= f.text_area :note, class: "form-control" %>
      
      
      <%= f.submit "メモ作成", class:"btn btn-lg btn-primary btn-block btn-signup" %>
      <% end %>
     
  </div>
</div>

app/views/memos/show.html.erb
<% provide(:title, 'Show Memo') %>
<h1>メモ詳細</h1>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-bordered" id="table-users">
        <tr>
          <th class="active col-md-2">ID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th class="active">タイトル</th>
          <td><%= @memo.title %></td>
        </tr>
        <tr>
          <th class="active">内容</tf>
          <td><%= @memo.note %></td>
        </tr>
        <tr>
          <th class="active">作成日</th>
          <td><%= l(@memo.created_at, format: :long) %></td>
        </tr>
        <tr>
          <th class="active">更新日</th>
          <td><%= l(@memo.updated_at, format: :long) %></td>
        </tr>
      </table>
      <%= link_to "編集", edit_user_memo_path, class: "btn btn-lg btn-success" %>
      <%= link_to "削除", user_memo_path, method: :delete, class: "btn btn-lg btn-danger",
          data: { confirm: "#{@memo.title}を削除してもよろしいですか？"} %>
      <%= link_to "メモ一覧", user_memos_path(@current_user), class: "btn btn-lg btn-primary" %>
    </div>    
　</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力エラーが<%= @user.errors.count %>件ありました
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/top.html.erb
<% provide(:title, "Top") %>
<div class="center jumbotron">
<h1>メモアプリ</h1>
<p>たくさんメモしましょう！！</p>
<%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %>
<p>ユーザー登録がまだの方は<%= link_to "こちら", signup_path %></p>
 </div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      
      <%= f.label :name, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :name, class: "form-control" %>
        
      <%= f.label :email, class: "label-#{yield(:class_text)}" %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :password, class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      
      <%= f.submit yield(:button_text), class:"btn btn-lg btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, '更新') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '全てのユーザー') %>
<h1>ユーザー一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= will_paginate %>
    <table class="table table-condensed table-hover" id="table-users">
      <thead>
        <tr>
          <th>名前</th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><% if current_user.admin? && !current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
            <% end %>
        </td>
      </tr>
      <% end %>
    </table>
    <%= will_paginate %>
  </div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>My アカウント</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-bordered" id="table-user">
      <tr>
        <th class="active col-md-3"><%= User.human_attribute_name :id %></th>
        <td class="col-md-9"><%= @user.id %></td>
      </tr>
      <tr>
        <th class="active"><%= User.human_attribute_name :name %></th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th class="active"><%= User.human_attribute_name :email %></th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th class="active"><%= User.human_attribute_name :created_at %></th>
        <td><%= l(@user.created_at, format: :long) %></td>
      </tr>
    </table>
  </div>    
</div>